### ISSUE TITLE
"opam install finch" results in "[ERROR] No package named finch found."

### ISSUE THREAD

**Issue by garyrob** [roddyyaga/finch#1]
I'm very interested in trying finch. I ran `opam install finch` using opam version 2.07 on MacOS and  opam version 1.2.2 on Ubuntu. In both cases, the response is "[ERROR] No package named finch found."

Any ideas?

**Comment by roddyyaga** [comment]
Glad to hear you're interested in it! You might need to do `opam update` first (and also possibly use opam 2.x on Ubuntu). You'll also need to use a copy of OCaml with version >= 4.07 (although failure to do this wouldn't cause that error). You can get one with `opam switch 4.xx.x`, creating the switch first if necessary (you can view existing switches with `opam switch`).

**Comment by garyrob** [comment]
Ah! As you can guess, I'm a newbie in the Ocaml world. And doing `opam update` and then `opam upgrade` did, of course, fix it.

For your amusement I'll tell a little story. I've been reading about Ocaml/reasomml and thinking that maybe I'd like to switch from Python to Ocaml. I've been using Python for probably 25 years now as my main language. It happens that I have the need to make a static web site and I was looking at staticjinja, which looks a lot like finch but python-based. But on around the second page of their docs, one of the examples doesn't work and is obviously wrong. I posted a github issue about it, and 10 days later there is no response from a developer—the only response is from another user pointing to another issue about the docs.

Your quick and friendly response to my issue may therefore mean I use finch instead, which would mean I am actually using Ocaml in real work. And doing that once may be the thing that ultimately causes me to move the center of my programming world from Python to Ocaml. (I have the freedom to choose whatever tools I want, and am very interested in moving to functional programming.)

So your nice response may have a bigger effect than you expected (at least on one person)... :)

I'll be checking finch out now that I've got it installed!
