### ISSUE TITLE
hugo comparison

### ISSUE THREAD

**Issue by ghost** [roddyyaga/finch#2]
I am curious about the following:

- relative to hugo, what features have you implemented? what's missing? which missing items are on the tentative roadmap?

**Comment by ghost** [comment]
I don't want to use your time answering this just yet. I will learn about hugo first.

**Comment by ghost** [comment]
I created this issue because I was researching possibilities for modernizing ocaml.org implementation, if momentum builds to update it. I would currently recommend hugo or next.js, but if you are interested in actively building up finch and you build up some of hugo's functionality, using finch could become suitable for ocaml.org. I have no idea if ocaml.org rewrite will gain momentum any time soon.

**Comment by roddyyaga** [comment]
Oh cool! It definitely has fewer features than hugo based on the amount of time put into the two projects; currently I'm mostly adding stuff that I want for my personal blog but I would be open to adding other features (don't have huge amounts of time though). I am not super familiar with hugo but I would expect a rewrite to use finch would not be significantly more effort than one to use hugo if done by people who know OCaml and are willing to contribute to finch if necessary (contributions are very welcome!)
